version: '3.4'

services:

  distributedcache:
    container_name: distributedcache
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  ordersdb:
    container_name: ordersdb
    image: mongo:7
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - orders_mongo:/data/db

  catalog.api:
    container_name: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog_API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__CatalogDb: "Host=ep-sweet-moon-axdkek5x-pooler.c-4.us-east-2.aws.neon.tech;Port=5432;Database=neondb;Username=neondb_owner;Password=npg_Cy4KMHlgz3hD;SSL Mode=Require"
    ports:
      - "6000:8080"
      - "6060:8081"

  basket.api:
    container_name: basket.api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_HTTPS_PORTS: 8081
      ConnectionStrings__Database: "Host=ep-sweet-moon-axdkek5x-pooler.c-4.us-east-2.aws.neon.tech;Port=5432;Database=neondb;Username=neondb_owner;Password=npg_Cy4KMHlgz3hD;SSL Mode=Require"
      ConnectionStrings__Redis: "distributedcache:6379"
    depends_on:
      - distributedcache
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  orders.api:
    container_name: orders.api
    build:
      context: .
      dockerfile: Services/Orders/Orders_API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      BasketApi__BaseUrl: "http://basket.api:8080"
      MongoDb__ConnectionString: "mongodb+srv://user:B4p1MdiI4yl682ue@cluster0.jhndu.mongodb.net/?appName=Cluster0"
      MongoDb__DatabaseName: "OrdersDb"
    ports:
      - "6002:8080"
      - "6062:8081"

volumes:
  orders_mongo: