version: '3.4'

services:
  catalogdb:
    image: postgres:15
  basketdb:
    image: postgres:15
  distributedcache:
    image: redis
  ordersdb:
    image: mongo:7
    ports:
      - "27017:27017"
  basket.api:
    image: ${DOCKER_REGISTRY-}basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile


volumes:
  postgres_catalog:
  postgres_basket:
  orders_mongo: